### ISSUE TITLE
Cannot start little-brother.

### ISSUE THREAD

**Issue by SolidSouless** [marcus67/little_brother#104]
Installed little-brother_0.3.4_76.deb.  little-brother_0.3.5_77 would not install. python2-dev depend could not be met. I try to start little-brother with 'systemctl start little-brother' but get 

"failed to add /run/systemd/ask-password to directory watch: no such file or directory
Failed to start little-brother.service :launch helper exited with unknown return code 1
See system logs and 'systemctl status little-brother.service' for details." 

I don't know to proceed or how to view the error. 

P.S. I am also having trouble installing little-brother taskbar, but I don't know if i should mention that here or make another Issue.
Thanks for any help :)

**Comment by marcus67** [comment]
Hi SolidSouless,

 

thank you for mail. I apologize for the delay but I have been on vacation.

 

Could you send me some details about the distribution and version that you are using?

 

Please, create separate issue for the taskbar here: https://github.com/marcus67/little_brother_taskbar/issues

 

Warm regards,

Marcus

 

Von: SolidSouless <notifications@github.com>
Antworten an: marcus67/little_brother <reply@reply.github.com>
Datum: Sonntag, 25. Oktober 2020 um 18:30
An: marcus67/little_brother <little_brother@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [marcus67/little_brother] Cannot start little-brother. (#104)

 

Installed little-brother_0.3.4_76.deb. little-brother_0.3.5_77 would not install. python2-dev depend could not be met. I try to start little-brother with 'systemctl start little-brother' but get

"failed to add /run/systemd/ask-password to directory watch: no such file or directory
Failed to start little-brother.service :launch helper exited with unknown return code 1
See system logs and 'systemctl status little-brother.service' for details."

I don't know to proceed or how to view the error.

P.S. I am also having trouble installing little-brother taskbar, but I don't know if i should mention that here or make another Issue.
Thanks for any help :)

**Comment by SolidSouless** [comment]
I'm using GalliumOS on a Chromebook. the newest version won't install because of Python2-dev. But the previous version i ended up to get working. Thanks :)

**Comment by marcus67** [comment]
Hi SolidSouless,
I just checked GalliumOS seems to be based on Xubuntu which is based on Ubuntu. Ubuntu does have a python2-dev package, so I'm afraid I don't know what went wrong. Do you remember the exact error? Was GalliumOS complaining about the package missing as such or was there a version clash? Thanks a lot!

**Comment by SolidSouless** [comment]
It says that the python2-dev package is not installed.

**Comment by MrFly** [comment]
> It says that the python2-dev package is not installed.

Shouldn't this be python3-dev?

**Comment by marcus67** [comment]
Packages python-dev and/or python2-dev are no longer required by the dependencies of the Debian package.
