### ISSUE TITLE
Controll little_brother remotely. Computer on other network. Different IP adress location?

### ISSUE THREAD

**Issue by SolidSouless** [marcus67/little_brother#105]
I want to be able to make changes/updates to little_brother from another computer. On the same network, but also on separate networks over the internet; would be something I would like to do. Is this at all currently possable?

**Comment by marcus67** [comment]
Hi SolidSouless, 

in principle there are no restrictions as to from where little_brother can be controlled. If the master is running on a machine that is reachable over the internet that should work fine. However, currently no HTTPS connections are possible, so you probably do not want to make your master interface available openly on the internet.

A safe way to do this would be to have a web server (e.g. Apache or nginx) to act as a reverse proxy. It would terminate the incoming SSL connection and forward the request to the local little_brother master host. Try to find a good introduction to reverse proxying (e.g. https://www.jamescoyle.net/how-to/116-simple-apache-reverse-proxy-example) and also see the section "Running behind a reverse proxy" on page https://github.com/marcus67/little_brother/blob/master/ADVANCED_TOPICS.md.
