### ISSUE TITLE
Lost ability to connect to master

### ISSUE THREAD

**Issue by bhulsken** [marcus67/little_brother#143]
getting the below errors after upgrade from 0.4.0 to 0.4.2, haven't been able to debug more for now. Nothing shows up in the backend with "DEBUG" loglevel.

021-05-26 16:59:06,085 - MasterConnector - DEBUG - Executing POST API call 'http://censored:5555/api/events'
2021-05-26 16:59:06,093 - MasterConnector - ERROR - Unknown error code '400' with message 'None' while accessing artifact 'http://censored:5555/api/events'

**Comment by marcus67** [comment]
Hi Bas,

this is my fault. Unfortunately, there was no test case for the slave/master communication. The error is triggered by the CSRF checks which I reactivated in the most recent version. I already fixed this in my local code yesterday. I will release the fix tonight. Sorry!
