### ISSUE TITLE
prometheus metrics missing

### ISSUE THREAD

**Issue by bhulsken** [marcus67/little_brother#149]
I think for the last few releases, a lot of the metrics are no longer exposed via prometheus (or set incorrectly to 0).

haven't really had the time to debug, but I get "configured users 0.0" (see below), while there are configured users, and earlier versions always gave a lot of metrics as output. Same for monitored devices, etc. I do get the correct python / little brother version and cpu load metrics.

response to curl -w '\n' http://localhost:8888:

<pre>
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 350734.0
python_gc_objects_collected_total{generation="1"} 186898.0
python_gc_objects_collected_total{generation="2"} 22627.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 1779.0
python_gc_collections_total{generation="1"} 161.0
python_gc_collections_total{generation="2"} 10.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="9",patchlevel="5",version="3.9.5"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 6.93436416e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.134656e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.62520997639e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 39.75
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 9.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1024.0
# HELP little_brother_monitored_users number of monitored users
# TYPE little_brother_monitored_users gauge
little_brother_monitored_users 0.0
# HELP little_brother_active_users number of active users
# TYPE little_brother_active_users gauge
# HELP little_brother_configured_users number of configured users
# TYPE little_brother_configured_users gauge
little_brother_configured_users 0.0
# HELP little_brother_monitored_hosts number of monitored hosts
# TYPE little_brother_monitored_hosts gauge
# HELP little_brother_monitored_devices number of monitored devices
# TYPE little_brother_monitored_devices gauge
little_brother_monitored_devices 0.0
# HELP little_brother_active_devices number of active devices
# TYPE little_brother_active_devices gauge
# HELP little_brother_device_response_time response time of device [ms]
# TYPE little_brother_device_response_time gauge
# HELP little_brother_device_moving_average_response_time moving average of response time of device [ms]
# TYPE little_brother_device_moving_average_response_time gauge
# HELP little_brother_forced_logouts_total number of forced logouts
# TYPE little_brother_forced_logouts_total counter
# HELP little_brother_http_requests request duration [ms] and count
# TYPE little_brother_http_requests summary
# HELP little_brother_system_info system information
# TYPE little_brother_system_info gauge
little_brother_system_info{revision="102",version="0.4.6"} 1.0
# HELP little_brother_uptime uptime in seconds
# TYPE little_brother_uptime gauge
# HELP node_process_resident_memory_bytes resident memory in bytes on node
# TYPE node_process_resident_memory_bytes gauge
# HELP node_process_cpu_seconds_total CPU time in seconds on node on node
# TYPE node_process_cpu_seconds_total gauge

</pre>

**Comment by marcus67** [comment]
Hi Bas, thank you for reporting this bug. It looks strange since the documentation of the metrics shows up in the list but not the metrics themselves. I will look into this.
