### ISSUE TITLE
HTTP call from client to master hangs for too long in case of timeout

### ISSUE THREAD

**Issue by marcus67** [marcus67/little_brother#174]
An unresponsive master can cause the client to wait for a response for up to 100 seconds or more. This screws up the timing and makes the client unresponsive to other tasks.
A quick fix would be to activate a maximum time of a configurable duration with a default of e.g. 5 seconds.

**Comment by marcus67** [comment]
Closed in eaae776b56b0003ff7478d1d7fa5e0b4b6a8ba81

**Comment by rosydawn6** [comment]
Confirmed in my 3 node client/server configuration that after overloading and restarting the server the clients are able to communicate effectively without a restart
