### ISSUE TITLE
little-brother.service does not start on Ubuntu 20.04.6 LTS 

### ISSUE THREAD

**Issue by 3eggert** [marcus67/little_brother#180]
```
root@bonb:~# systemctl restart little-brother 
Job for little-brother.service failed because the control process exited with error code.
See "systemctl status little-brother.service" and "journalctl -xe" for details.
root@bonb:~# 

 
root@bonb:~# systemctl status little-brother.service
● little-brother.service - Tool for monitoring processes
     Loaded: loaded (/lib/systemd/system/little-brother.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-08-25 15:42:04 CEST; 14s ago
    Process: 1565 ExecStart=/usr/local/bin/run_little_brother.py --daemonize --pidfile=/run/little-brother/little-brother.pid --config=/etc/little-brother/little-brother.config --logdir=/var/log/little-brother --create-databases --upgrade>

Aug 25 15:42:04 bonb run_little_brother.py[1565]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/admin_event.py", line 20, in <module>
Aug 25 15:42:04 bonb run_little_brother.py[1565]:     from little_brother import process_info
Aug 25 15:42:04 bonb run_little_brother.py[1565]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/process_info.py", line 18, in <module>
Aug 25 15:42:04 bonb run_little_brother.py[1565]:     from python_base_app import tools
Aug 25 15:42:04 bonb run_little_brother.py[1565]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/tools.py", line 518, in <module>
Aug 25 15:42:04 bonb run_little_brother.py[1565]:     def get_ip_addresses_by_dns_name(p_dns_name: str) -> set[str]:
Aug 25 15:42:04 bonb run_little_brother.py[1565]: TypeError: 'type' object is not subscriptable
Aug 25 15:42:04 bonb systemd[1]: little-brother.service: Control process exited, code=exited, status=1/FAILURE
Aug 25 15:42:04 bonb systemd[1]: little-brother.service: Failed with result 'exit-code'.
Aug 25 15:42:04 bonb systemd[1]: Failed to start Tool for monitoring processes.
root@bonb:~# 


root@bonb:~# cat /etc/issue
Ubuntu 20.04.6 LTS \n \l

root@bonb:~# 



```
Any hints how to fix it?

**Comment by marcus67** [comment]
@3eggert : This seems to be a Python version issue since it occurs while Python reads the import statements. The expression `set[str]` seems to be too modern. I will double-check and get back to you.

**Comment by marcus67** [comment]
I got the confirmation. It's a Python version problem. I'll remove the parts which are incompatible with Python 3.8.

**Comment by 3eggert** [comment]
Thanks for the quick response, but 0.4.28 did not fix the issue:
root@bonb:~# apt search little-brother 
Sorting... Done
Full Text Search... Done
little-brother/now 0.4.28-135 all [installed,local]
  Tool to monitor login time of users on Debian hosts and terminate processes if usage times are exceeded. Note that this package is not meant as a simple install with PIP since it also requires additional work in the operating system (e.g. add a user, create directories, define a startup service). This is all done by the Debian package provided at https://sourceforge.net/projects/little-brother/ .

root@bonb:~# systemctl status little-brother.service
● little-brother.service - Tool for monitoring processes
     Loaded: loaded (/lib/systemd/system/little-brother.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-08-31 12:17:54 CEST; 1min 45s ago
    Process: 2054 ExecStart=/usr/local/bin/run_little_brother.py --daemonize --pidfile=/run/little-brother/little-brother.pid --config=/etc/little-brother/little-brother.config --logdir=/var/log/little-brother --create-databases --upgra>

Aug 31 12:17:54 bonb run_little_brother.py[2054]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/admin_event.py", line 20, in <module>
Aug 31 12:17:54 bonb run_little_brother.py[2054]:     from little_brother import process_info
Aug 31 12:17:54 bonb run_little_brother.py[2054]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/process_info.py", line 18, in <module>
Aug 31 12:17:54 bonb run_little_brother.py[2054]:     from python_base_app import tools
Aug 31 12:17:54 bonb run_little_brother.py[2054]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/python_base_app/tools.py", line 518, in <module>
Aug 31 12:17:54 bonb run_little_brother.py[2054]:     def get_ip_addresses_by_dns_name(p_dns_name: str) -> set[str]:
Aug 31 12:17:54 bonb run_little_brother.py[2054]: TypeError: 'type' object is not subscriptable
Aug 31 12:17:54 bonb systemd[1]: little-brother.service: Control process exited, code=exited, status=1/FAILURE
Aug 31 12:17:54 bonb systemd[1]: little-brother.service: Failed with result 'exit-code'.
Aug 31 12:17:54 bonb systemd[1]: Failed to start Tool for monitoring processes.
root@bonb:~#

**Comment by marcus67** [comment]
@3eggert : Sorry about this. The package had been corrected but due to an error of mine the previous version of the package was included into the Debian package.

**Comment by marcus67** [comment]
@3eggert : Please, try version 0.4.29.

**Comment by 3eggert** [comment]
still no change:

root@bonb:~# dpkg -i ~eggert/little-brother_0.4.29_136.deb 
(Reading database ... 214748 files and directories currently installed.)
Preparing to unpack .../little-brother_0.4.29_136.deb ...
Unpacking little-brother (0.4.29-136) over (0.4.29-136) ...
Setting up little-brother (0.4.29-136) ...

....

root@bonb:~# systemctl restart little-brother 
Job for little-brother.service failed because the control process exited with error code.
See "systemctl status little-brother.service" and "journalctl -xe" for details.

root@bonb:~# systemctl status little-brother.service
● little-brother.service - Tool for monitoring processes
     Loaded: loaded (/lib/systemd/system/little-brother.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2023-09-07 12:07:33 CEST; 7s ago
    Process: 23278 ExecStart=/usr/local/bin/run_little_brother.py --daemonize --pidfile=/run/little-brother/little-brother.pid --config=/etc/little-brother/little-brother.config --logdir=/var/log/little-brothe>

Sep 07 12:07:33 bonb run_little_brother.py[23278]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/persistence/persistent_device_entity_manager.py", line 20, in <module>
Sep 07 12:07:33 bonb run_little_brother.py[23278]:     from little_brother.persistence.persistent_device import Device
Sep 07 12:07:33 bonb run_little_brother.py[23278]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/persistence/persistent_device.py", line 30, in <module>
Sep 07 12:07:33 bonb run_little_brother.py[23278]:     class Device(Base, BaseEntity):
Sep 07 12:07:33 bonb run_little_brother.py[23278]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/little_brother/persistence/persistent_device.py", line 76, in Device
Sep 07 12:07:33 bonb run_little_brother.py[23278]:     def list_of_blocked_ip_addresses(self) -> list[str]:
Sep 07 12:07:33 bonb run_little_brother.py[23278]: TypeError: 'type' object is not subscriptable
Sep 07 12:07:33 bonb systemd[1]: little-brother.service: Control process exited, code=exited, status=1/FAILURE
Sep 07 12:07:33 bonb systemd[1]: little-brother.service: Failed with result 'exit-code'.
Sep 07 12:07:33 bonb systemd[1]: Failed to start Tool for monitoring processes.
root@bonb:~#

**Comment by marcus67** [comment]
Hi @3eggert : This is actually a similar error in a different location. Apparently, my code is lacking some test cases...

**Comment by marcus67** [comment]
Apparently, I concentrated my Python 8 checks on `python_base_app` but there were issues in little_brother, too. I just released version 0.4.30 which should take care of the incompatibilities. It will be available in a few minutes. Sorry for the inconvenience.

**Comment by 3eggert** [comment]
Thanks for the support,
that changes the error:
`
root@bonb:~# systemctl status little-brother.service
● little-brother.service - Tool for monitoring processes
     Loaded: loaded (/lib/systemd/system/little-brother.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-10-06 12:16:18 CEST; 11s ago
    Process: 28057 ExecStart=/usr/local/bin/run_little_brother.py --daemonize --pidfile=/run/little-brother/little-brother.pid --config=/etc/little-brother/little-brother.config --logdir=/var/log/little-brother --create-databases --upgr>

Okt 06 12:16:18 bonb run_little_brother.py[28057]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/flask_login/__init__.py", line 12, in <module>
Okt 06 12:16:18 bonb run_little_brother.py[28057]:     from .login_manager import LoginManager
Okt 06 12:16:18 bonb run_little_brother.py[28057]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/flask_login/login_manager.py", line 33, in <module>
Okt 06 12:16:18 bonb run_little_brother.py[28057]:     from .utils import _create_identifier
Okt 06 12:16:18 bonb run_little_brother.py[28057]:   File "/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/flask_login/utils.py", line 14, in <module>
Okt 06 12:16:18 bonb run_little_brother.py[28057]:     from werkzeug.urls import url_decode
Okt 06 12:16:18 bonb run_little_brother.py[28057]: ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/var/lib/little-brother/virtualenv/lib/python3.8/site-packages/werkzeug/urls.py)
Okt 06 12:16:18 bonb systemd[1]: little-brother.service: Control process exited, code=exited, status=1/FAILURE
Okt 06 12:16:18 bonb systemd[1]: little-brother.service: Failed with result 'exit-code'.
Okt 06 12:16:18 bonb systemd[1]: Failed to start Tool for monitoring processes.
`

I saw the issue ticked for that one, I'll try the purposed solution

**Comment by marcus67** [comment]
@3eggert Sorry again. I screwed up the package version. There will be a fix soon.
