### ISSUE TITLE
Logout when network connectivity is lost

### ISSUE THREAD

**Issue by marcus67** [marcus67/little_brother#20]
Current behavior: when network connectivity is lost slaves will never be informed about exceeded ligin times. Hence, monitored users will not be logged out. This might be an “attack vector” by users.
Desired behavior: it should be possible to optionally configure the application to log out after the network connectivity has been lost for more than N minutes.

**Comment by vaidls** [comment]
Hello,
I can confirm that my children has discover this feature/bug and using it actively.

Could you add this feature to application.

Thank you.

**Comment by marcus67** [comment]
@vaidls In principle this feature should always be active. But let me double-check I haven't seen in us for quite some time.
