### ISSUE TITLE
Message per popup

### ISSUE THREAD

**Issue by marcus67** [marcus67/little_brother#6]
Current behavior: Feedback to the user is only given by spoken messages which might not be audible depending on the audio settings.
Desired behavior: Optionally, it should be possible to have a popup inform the user about impending logouts.

See https://superuser.com/questions/309961/linux-how-to-send-message-to-local-user-logged-into-x11

**Comment by bgstack15** [comment]
Alternatives include zenity or yad. Perhaps this could be configured as conf file options:
```
osd_message_binary='DISPLAY=$USERDISPLAY /usr/bin/yad --options --moreoptions $MESSAGE'
osd_messages = {
 'warning1': "You have 15 minutes remaining",
 'warning2': "You have 5 minutes remaining",
 'expired': "Time is up!"
}
```
And the program derives the $USERDISPLAY and substitutes the right $MESSAGE of course.
I don't know to recommend if any such options would be server-side or client-side.

**Comment by marcus67** [comment]
@bgstack15: Thank you for the links! The main issue will be security, though. LittleBrother runs with normal user permissions and won’t be able to create an x-window-client. Probably, for monitored users a call to xauth will have to be included into the session scripts.

**Comment by marcus67** [comment]
@bgstack15 : The latest "master" version covers your requirement. I would be happy about a test. :-)

**Comment by marcus67** [comment]
Stupid me! I tested the new version with the DISPLAY variable set. Of course, in a system daemon setting this has to be done explicitly!

**Comment by marcus67** [comment]
A short description about additional configuration required to use popups has been added to the README.md file.
