### ISSUE TITLE
Cannot install pyobjc-framework-CoreAudioKit

### ISSUE THREAD

**Issue by dgofman** [marcus67/little_brother#67]
Collecting pyobjc-framework-CoreAudioKit==6.1
  Downloading pyobjc-framework-CoreAudioKit-6.1.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/pip-egg-info
         cwd: /tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/setup.py", line 33, in <module>
        for fn in os.listdir("Modules")
      File "/tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/pyobjc_setup.py", line 408, in Extension
        os_level = get_os_level()
      File "/tmp/pip-install-4zrugjzk/pyobjc-framework-CoreAudioKit/pyobjc_setup.py", line 218, in get_os_level
        pl = plistlib.readPlist("/System/Library/CoreServices/SystemVersion.plist")
      File "/usr/lib/python3.6/plistlib.py", line 162, in readPlist
        with _maybe_open(pathOrFile, 'rb') as fp:
      File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
        return next(self.gen)
      File "/usr/lib/python3.6/plistlib.py", line 120, in _maybe_open
        with open(pathOrFile, mode) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
dpkg: error processing package little-brother (--configure):
 installed little-brother package post-installation script subprocess returned error exit status 1
Setting up dh-python (3.20180325ubuntu2) ...
Setting up libpython3-dev:amd64 (3.6.7-1~18.04) ...
Setting up python3-cryptography (2.1.4-1ubuntu1.3) ...
Setting up python3-keyrings.alt (3.0-1) ...
Setting up python3-dev (3.6.7-1~18.04) ...
Setting up python3-secretstorage (2.3.1-2) ...
Setting up python3-keyring (10.6.0-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 little-brother
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by marcus67** [comment]
Hi David, thank you for reporting this issue. Could you add some details about the Linux distribution and the release of LittleBrother that you are using? Thanks!

**Comment by dgofman** [comment]
Hi Marcus,
I tried to use all available solutions on my Ubuntu, However, is impossible to install pyobjc on Ubuntu "ERROR: Requires macOS to install or build". Can you check your scripts I used deb 39 based on your video up to latest one https://sourceforge.net/projects/little-brother/

uname -a
34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux



sudo apt-get install build-essential autoconf libtool pkg-config python-opengl python-pil python-pyrex python-pyside.qtopengl idle-python2.7 qt4-dev-tools qt4-designer libqtgui4 libqtcore4 libqt4-xml libqt4-test libqt4-script libqt4-network libqt4-dbus python-qt4 python-qt4-gl libgle3 python-dev libssl-dev libpq-dev libxml2-dev libxslt1-dev libldap2-dev libsasl2-dev libffi-dev gcc


$ sudo apt-get install python-dateutil python-docutils python-feedparser python-gdata python-jinja2 python-ldap python-libxslt1 python-lxml python-mako python-mock python-openid python-psycopg2 python-psutil python-pychart python-pydot python-pyparsing python-reportlab python-simplejson python-tz python-unittest2 python-vatnumber python-vobject python-webdav python-werkzeug python-xlwt python-yaml python-zsi

**Comment by dgofman** [comment]
I will upgrade to 19.10 and will run again your installation script

**Comment by marcus67** [comment]
OK. I will have to check which explicit dependency will trigger pyobjc. From your log it seems to be related to audio handling. I've had a LOT of trouble with audio output. Maybe it's time to throw some of the stuff out...

**Comment by marcus67** [comment]
I just checked the latest install log for Debian. There's no pyobjc showing up at all. I'm not quite sure why it should occur under Ubuntu. I will check on my Ubuntu virtual machine tomorrow night. It's too late tonight.

**Comment by dgofman** [comment]
Thanks!

**Comment by dgofman** [comment]
I upgraded to Ubuntu 19.10 and got the same issue.

**Comment by marcus67** [comment]
Haven't forgotten this. Tried to install image Ubuntu 19.10 in a VM but the system hang during installation of the Ubuntu system. Will have try something else...

**Comment by dgofman** [comment]
I was able to update 18.4 to 19.10, however, after installing your DPKG my system was corrupted and I had only one way to recover my system after a reboot using the next commands:
sudo dpkg --configure -a
sudo apt-get install --reinstall ubuntu-desktop
restart your computer and go to desktop

**Comment by marcus67** [comment]
The error is caused by the dependencies of module `pyttsx3`. I removed this module from the application.
In what way was your system corrupted?

**Comment by dgofman** [comment]
Please, can you provide a link for your DEB file

**Comment by marcus67** [comment]
You can download the latest version from https://sourceforge.net/projects/little-brother/files/master/. It should eliminate the problem with module `pyttsx3`. However, this revision (54) is pretty makeshift since it contains a badly tested version of the new tray app. You may want to wait until tomorrow get get revision 55.

**Comment by marcus67** [comment]
Hi David,

I would like to follow up on this issue after along time. I hope you don't mind.

Do you happen to remember in what way your system was corrupted? 

I'm asking now because I just had trouble myself because the old version of the Debian package called 'pip install' with very specific versions of a range of Python modules which conflicted with other applications.

I'm wondering if you had a similar problem? If so, version 0.3 will bring a remedy to this by installing a virtual Python environment.

See https://github.com/marcus67/little_brother/issues/93

Warm regards,

Marcus
