### ISSUE TITLE
Please can you customize the geometry of popup window

### ISSUE THREAD

**Issue by dgofman** [marcus67/little_brother#68]
zenity --warning --title="Zenity | Workaround excessive height" --width=100 --height=100 --no-wrap --text="<big><b>Zenity problem:\n Excessive height with long text.</b></big>\n\nSomehow Zenity's option '<b>--height</b>' doesn't seem to do the job.\nHowever, this doesn't have to spoil your fun! Omit the '<b>--width</b>'\nand '<b>--height</b>' option or set it to the minimum value you require.\nAnd add the '<b>--no-wrap</b>' option. Now use '<b>\\\n</b>' wherever you want\nto break the line (sentence). The width of the popup will adjust\nitself to the longest sentence."

**Comment by marcus67** [comment]
I will provide configuration settings for width and height and try to incorporate your suggestions. However, the popup window will become obsolete by the new taskbar tray app which is already included in the new version of the app. The documentation is still missing. I will provide this over the next couple of days.

**Comment by marcus67** [comment]
Your suggestions have been incorporated. However, as mentioned before, the popup windows have been replaced by [LittleBrotherTaskbar](https://github.com/marcus67/little_brother_taskbar).
